### ISSUE TITLE
Two columns of line numbers show on Atom 1.13.0

### ISSUE THREAD

**Issue by moskyb** [justmoon/relative-numbers#25]
MacOS Sierra 10.12.2
Atom 1.13.0
relative-numbers 0.6.0

As shown below, on Atom 1.13.0, relative-numbers shows two columns of line numbers - one relative and one absolute
![screen shot 2017-01-11 at 3 33 15 pm](https://cloud.githubusercontent.com/assets/15753101/21832928/6fc8c132-d813-11e6-85bc-dc38d1675b1d.png)

**Comment by sergiouve** [comment]
Same on Fedora, and I'll take a wild guess and say that this issue is platform independent.

It's probably related to [Atom removing Shadow DOM boundaries](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html) since this package uses them to render the line numbers in the gutter.
